export default function Disclaimer() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-16 text-gray-700 leading-relaxed">
      <h1 className="text-4xl font-black text-gray-900 mb-8 border-b pb-4">Disclaimer</h1>
      <p className="text-sm text-gray-400 mb-10 uppercase tracking-widest font-bold">Last Updated: April 2026</p>

      <div className="space-y-8">
        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Not Financial Advice</h2>
          <p>
            The content on <strong>Finance Tool Pro</strong> is provided for informational and educational purposes only. I am a software developer, not a certified financial advisor, accountant, or attorney. The calculations generated by our tools are estimates based on standard formulas and should not be construed as professional financial advice.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Accuracy of Information</h2>
          <p>
            While I strive to ensure that the math behind these tools is as accurate as possible, financial markets, interest rates, and tax laws change rapidly. <strong>Finance Tool Pro</strong> cannot guarantee that all results are 100% accurate or up-to-date at the moment of use. Always verify the results with a qualified professional before making any major financial commitments.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">3. External Links</h2>
          <p>
            From time to time, this website may include links to other websites. These links are provided for your convenience to provide further information. I have no responsibility for the content of the linked website(s) and do not endorse them.
          </p>
        </section>

        <section className="bg-red-50 p-6 rounded-2xl border border-red-100">
          <h2 className="text-xl font-bold text-red-900 mb-2">4. "Use at Your Own Risk"</h2>
          <p className="text-red-800 text-sm">
            By using this site, you agree that <strong>Finance Tool Pro</strong> will not be held liable for any decisions made or actions taken based on the information provided by our calculators. Your financial health is your responsibility—please do your due diligence.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Contact Me</h2>
          <p>
            If you have any questions regarding this disclaimer, please reach out via email at <a href="mailto:hezhanleiok@gmail.com" className="text-blue-600 font-bold hover:underline">hezhanleiok@gmail.com</a>.
          </p>
        </section>
      </div>
    </div>
  );
}